version: '3'

services:
  
  php-apache:
    container_name: php7_php-apache
    build: ./dockerfiles/php7.2
    restart: on-failure
    environment:
      APACHE_RUN_USER: www
      APACHE_RUN_GROUP: www
    ports:
      - 80:80
    depends_on:
      - mysql
    volumes:
      # configs
      - ./configs/apache2:/etc/apache2
      - ./configs/php:/usr/local/etc/php
      # xdebug profiler
      - ./xdebug-profiler:/tmp/xdebug
      # logs
      - ./logs/apache2:/var/log/apache2
      # projects
      - ~/projects:/var/www

  mysql:
    container_name: php7_mysql
    build: ./dockerfiles/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./configs/mysql:/etc/mysql/conf.d
      - ./databases:/var/lib/mysql
      - ./databases_backups:/backups
    
  adminer:
    container_name: php7_adminer
    image: adminer
    restart: on-failure
    ports:
      - 8080:8080
    links:
      - mysql:db
            
